/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c3b4809d-a6cf-457e-b443-9ed77378fc97",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xp1VM2DOp",
    "aws_user_pools_web_client_id": "7l4m21fm6a986of15bfdhmuvv3",
    "oauth": {}
};


export default awsmobile;
